import{PAGE_SIZE}from"./state.js";import{SPECIAL_CHAR_REGEX}from"./utils.js";export function applyFallbackFont(e){if(!e)return;const t=[];const n=document.createTreeWalker(e,NodeFilter.SHOW_TEXT,{acceptNode:e=>{if(e.parentElement?.classList.contains("fallback-char")){return NodeFilter.FILTER_REJECT}SPECIAL_CHAR_REGEX.lastIndex=0;if(SPECIAL_CHAR_REGEX.test(e.textContent)){return NodeFilter.FILTER_ACCEPT}return NodeFilter.FILTER_SKIP}});let s;while(s=n.nextNode()){t.push(s)}t.forEach(e=>{const t=e.textContent;const n=e.parentNode;if(!n)return;const s=n.tagName==="MARK";const o=document.createDocumentFragment();let i=0;SPECIAL_CHAR_REGEX.lastIndex=0;let c;while((c=SPECIAL_CHAR_REGEX.exec(t))!==null){const a=c.index;if(a>i){o.appendChild(document.createTextNode(t.slice(i,a)))}const r=document.createElement("span");r.className="fallback-char";r.textContent=c[0];o.appendChild(r);i=a+c[0].length}if(i<t.length){o.appendChild(document.createTextNode(t.slice(i)))}if(s){const l=document.createElement("mark");l.appendChild(o);n.parentNode.replaceChild(l,n)}else{n.replaceChild(o,e)}})}export function renderOptions(l,d,e,t,n){const p=document.getElementById("options-container");p.innerHTML="";const s=e[d]||[];const u=l.answer.length>1;const g=n[d];s.forEach((e,t)=>{const s=l.options[e];let n=s.text;n=n.replace(/!\[(.*?)\]\((.*?)\)/g,(e,t,n)=>{return`<img src="${n}" alt="${t}" class="option-image">`});const o=document.createElement("div");o.className="option";const i=u?"checkbox":"radio";const c=u?"q-"+d:"question";const a="opt-"+d+"-"+t;const r=g?u?g.includes(s.value):g===s.value:false;o.innerHTML=`
      <input type="${i}" id="${a}" name="${c}" value="${s.value}" ${r?"checked":""}>
      <label for="${a}">${String.fromCharCode(65+t)}. ${n}</label>
    `;setTimeout(()=>{const e=o.querySelector("label");if(e&&e.offsetHeight>32){o.classList.add("multiline")}},10);o.querySelector("input").addEventListener("change",t=>{const n=s.value;if(u){const e=new CustomEvent("option-change",{detail:{index:d,value:n,isMulti:u,checked:t.target.checked}});document.dispatchEvent(e)}else{const e=new CustomEvent("option-change",{detail:{index:d,value:n,isMulti:false}});document.dispatchEvent(e)}});if(r)o.classList.add("selected");p.appendChild(o)})}export function updateSelectedOptions(){document.querySelectorAll(".option").forEach(e=>{const t=e.querySelector("input");if(t&&t.checked){e.classList.add("selected")}else{e.classList.remove("selected")}})}export function showPracticeFeedback(e){const t=document.getElementById("practice-feedback");t.classList.remove("correct","incorrect");if(e){t.textContent="回答正确";t.classList.add("correct")}else{t.textContent="回答错误，已记入错题本";t.classList.add("incorrect")}}export function showCorrectAnswerHint(e,t,n,s){const o=document.getElementById("correct-answer-hint");if(!o)return;if(t){o.style.display="none";return}const i=n[s]||{};const c=e.answer.split("").map(e=>i[e]||e).join("、");o.textContent="正确答案："+c;o.style.display="block"}export function renderProgress(e,t){document.getElementById("progress").textContent=e+1;document.getElementById("progress-fill").style.width=(e+1)/t*100+"%"}export function hideAllScreens(){document.getElementById("start-screen").classList.add("screen-hidden");document.getElementById("exam-screen").classList.add("screen-hidden");document.getElementById("result-screen").classList.add("screen-hidden")}export function showStartScreen(){hideAllScreens();document.getElementById("start-screen").classList.remove("screen-hidden")}export function showExamScreen(){hideAllScreens();document.getElementById("exam-screen").classList.remove("screen-hidden")}export function showResultScreen(){hideAllScreens();document.getElementById("result-screen").classList.remove("screen-hidden")}export function toggleLoadingOverlay(e,t="加载中..."){const n=document.getElementById("loading-overlay");document.getElementById("loading-message").textContent=t;if(e){n.classList.remove("hidden")}else{n.classList.add("hidden")}}export function renderHistory(e,n){const t=document.getElementById("history-list");if(!t)return;if(!e||e.length===0){t.innerHTML='<div style="text-align:center; color:#999; padding:20px;">暂无考试记录</div>';return}let i="";e.forEach((e,t)=>{const n=new Date(e.timestamp).toLocaleString();const s=e.passed?"history-pass":"history-fail";const o=e.passed?"合格":"不合格";i+=`
      <div class="history-item" data-idx="${t}">
        <div class="history-item-header">
          <input type="checkbox" class="history-checkbox" data-index="${t}" id="hist-cb-${t}">
          <label for="hist-cb-${t}" class="history-title">
            <strong>${e.type}类</strong>
            <span class="history-score">${e.score}/${e.total}</span>
            <span class="${s}">${o}</span>
            <span class="history-time">${e.timeUsedStr}</span>
          </label>
        </div>
        <div class="history-item-footer">
          <span class="history-date">${n}</span>
          ${e.wrongIds&&e.wrongIds.length?`<span class="history-view-wrong" data-idx="${t}">查看错题</span>`:""}
        </div>
      </div>
    `});t.innerHTML=i;t.querySelectorAll(".history-view-wrong").forEach(t=>{t.addEventListener("click",()=>{const e=parseInt(t.dataset.idx);if(!isNaN(e)&&n)n(e)})})}function renderPagination(t,n){if(n<=1)return"";let s='<div class="pagination-controls">';s+=`<button class="page-btn" data-page="prev" ${t===1?"disabled":""}>上一页</button>`;let o=[];if(n<=5){for(let e=1;e<=n;e++)o.push(e)}else if(t<=3){o=[1,2,3,4,"...",n]}else if(t>=n-2){o=[1,"...",n-3,n-2,n-1,n]}else{o=[1,"...",t-1,t,t+1,"...",n]}o.forEach(e=>{if(e==="..."){s+='<span class="page-ellipsis">...</span>'}else{s+=`<button class="page-btn" data-page="${e}" ${t===e?"disabled":""}>${e}</button>`}});s+=`<button class="page-btn" data-page="next" ${t===n?"disabled":""}>下一页</button>`;s+=`
    <span class="goto-box">
      跳至 <input type="number" id="page-goto-input" min="1" max="${n}" value="${t}" class="goto-input" style="width:60px;"> 页
      <button id="page-goto-btn" class="goto-btn">Go</button>
    </span>
  `;s+="</div>";return s}function loadSearchImages(e){e.querySelectorAll(".image-placeholder").forEach(t=>{const n=t.dataset.imgSrc;const e=new Image;e.onload=()=>{const e=document.createElement("img");e.src=n;e.loading="lazy";e.className="question-image";e.alt="题目配图";t.parentNode.replaceChild(e,t)};e.onerror=()=>t.remove();e.src=n})}export function renderSearchResults(e,t,n,s,o){const i=document.getElementById("query-results");const c=document.getElementById("query-pagination-top");if(!i){console.error("找不到 #query-results 元素");return}if(!c){console.error("找不到 #query-pagination-top 元素");return}c.onclick=null;c.onkeypress=null;if(!e||e.length===0){i.innerHTML='<p style="text-align:center; color:#7f8c8d;">未找到匹配的题目</p>';c.innerHTML="";return}const a=(n-1)*PAGE_SIZE;const r=a+PAGE_SIZE;const l=e.slice(a,r);if(s>1){c.innerHTML=renderPagination(n,s);c.onclick=function(e){const t=e.target.closest(".page-btn");if(t){const e=t.dataset.page;if(e==="prev"){if(n>1)o(n-1)}else if(e==="next"){if(n<s)o(n+1)}else if(e!=="..."){o(parseInt(e,10))}return}if(e.target.id==="page-goto-btn"||e.target.closest("#page-goto-btn")){const t=document.getElementById("page-goto-input");if(t){let e=parseInt(t.value,10);if(isNaN(e)||e<1)e=1;if(e>s)e=s;if(e!==n)o(e)}}};c.onkeypress=function(e){if(e.target.id==="page-goto-input"&&e.key==="Enter"){const e=document.getElementById("page-goto-btn");if(e)e.click()}}}else{c.innerHTML=""}let g="";const d=t.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const m=new RegExp("("+d+")","gi");l.forEach(({question:e,types:t})=>{const n=t.join("/");let s=e.question;const o=/\[image:\s*([^\]]+)\]/g;const i=[];let c=0;let a;while((a=o.exec(s))!==null){i.push(s.slice(c,a.index));i.push(`<span class="image-placeholder" data-img-src="static/img/${a[1]}"></span>`);c=a.index+a[0].length}i.push(s.slice(c));for(let e=0;e<i.length;e++){if(typeof i[e]==="string"&&!i[e].includes("image-placeholder")){i[e]=i[e].replace(m,"<mark>$1</mark>")}}const r=i.join("");let l="";e.options.forEach((e,t)=>{const n=String.fromCharCode(65+t);let s=e.text.replace(m,"<mark>$1</mark>");l+=`<div class="option" style="cursor:default;">${n}. ${s}</div>`});let d="";for(const p of e.answer){const u=e.options.findIndex(e=>e.value===p);if(u!==-1)d+=String.fromCharCode(65+u)}g+=`
      <div class="query-item">
        <div class="badge">${n}类题库</div>
        <h4>${e.id}</h4>
        <div class="question-text">${r}</div>
        <div class="options">${l}</div>
        <div class="correct-answer">正确答案：${d}</div>
      </div>
    `});i.innerHTML=g;applyFallbackFont(i);loadSearchImages(i)}